[package]
name = "wayland-kbd"
version = "0.1.1"
documentation = "http://vberger.github.io/wayland-kbd/wayland_kdb/"
repository = "https://github.com/vberger/wayland-kdb"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
description = "Keyboard mapping utility for wayland-client using libxkbcommon."

[dependencies]
bitflags = "0.1"
lazy_static = "0.1"
libc = "0.1"
mmap = "0.1"
wayland-client = "^0.1.6"

[dev-dependencies]
tempfile = "0.1"
